### ISSUE TITLE
error at compilation : trying to access to a protected variable

### ISSUE THREAD

**Issue by MTrac** [adepierre/Caffe_BEGAN#1]
Hello,

thank you for that library. 
I am trying to compile it : everything is fine with the "cmake .". When I push make I get : 

Scanning dependencies of target Caffe_BEGAN
[ 33%] Building CXX object CMakeFiles/Caffe_BEGAN.dir/src/NN_Agent.cpp.o
/path/to/Caffe_BEGAN/src/NN_Agent.cpp: In member function ‘void NN_Agent::Train(const std::vector<std::vector<float> >&, const std::vector<std::vector<float> >&)’:
/path/to/Caffe_BEGAN/src/NN_Agent.cpp:129:32: error: ‘void caffe::Solver<Dtype>::ApplyUpdate() [with Dtype = float]’ is protected within this context
  solver_generator->ApplyUpdate();
                                ^
In file included from /usr/include/caffe/caffe.hpp:15:0,
                 from /path/to/Caffe_BEGAN/include/NN_Agent.h:6,
                 from /path/to/Caffe_BEGAN/src/NN_Agent.cpp:1:
/usr/include/caffe/solver.hpp:99:16: note: declared protected here
   virtual void ApplyUpdate() = 0;
                ^~~~~~~~~~~
/path/to/Caffe_BEGAN/src/NN_Agent.cpp:130:20: error: ‘int caffe::Solver<float>::iter_’ is protected within this context
  solver_generator->iter_++;
                    ^~~~~
In file included from /usr/include/caffe/caffe.hpp:15:0,
                 from /path/to/Caffe_BEGAN/include/NN_Agent.h:6,
                 from /path/to/Caffe_BEGAN/src/NN_Agent.cpp:1:
/usr/include/caffe/solver.hpp:113:7: note: declared protected here
   int iter_;
       ^~~~~
/path/to/Caffe_BEGAN/src/NN_Agent.cpp:148:36: error: ‘void caffe::Solver<Dtype>::ApplyUpdate() [with Dtype = float]’ is protected within this context
  solver_discriminator->ApplyUpdate();
                                    ^
In file included from /usr/include/caffe/caffe.hpp:15:0,
                 from /path/to/Caffe_BEGAN/include/NN_Agent.h:6,
                 from /path/to/Caffe_BEGAN/src/NN_Agent.cpp:1:
/usr/include/caffe/solver.hpp:99:16: note: declared protected here
   virtual void ApplyUpdate() = 0;
                ^~~~~~~~~~~
/path/to/Caffe_BEGAN/src/NN_Agent.cpp:149:24: error: ‘int caffe::Solver<float>::iter_’ is protected within this context
  solver_discriminator->iter_++;
                        ^~~~~
In file included from /usr/include/caffe/caffe.hpp:15:0,
                 from /path/to/Caffe_BEGAN/include/NN_Agent.h:6,
                 from /path/to/Caffe_BEGAN/src/NN_Agent.cpp:1:
/usr/include/caffe/solver.hpp:113:7: note: declared protected here
   int iter_;
       ^~~~~
CMakeFiles/Caffe_BEGAN.dir/build.make:62: recipe for target 'CMakeFiles/Caffe_BEGAN.dir/src/NN_Agent.cpp.o' failed
make[2]: *** [CMakeFiles/Caffe_BEGAN.dir/src/NN_Agent.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Caffe_BEGAN.dir/all' failed
make[1]: *** [CMakeFiles/Caffe_BEGAN.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Do you have any idea of what happen ?.

Thank you for your time !

**Comment by adepierre** [comment]
Hi!

As described in the Dependencies part of the Readme, you need to perform two very small modifications on the source code of Caffe (file solver.hpp):

ApplyUpdate function must be moved from protected to public
iter_ must be moved from protected to public

It should solve your problem. Let me know if it doesn't !

**Comment by MTrac** [comment]
Thank you for your answer ! 
After some little adjustment more, it does now compile perfectly !
